const siteData={business:{name:"Beauty Secret Salon",location:"Kisaasi–Kyanja Road, at the junction to Komamboga, opposite Prime Petrol Station, Kampala, Uganda",primaryPhone:"0754 852 452",secondaryPhone:"0784 852 452",whatsappNumber:"256754852452",whatsappConfirmed:false},brand:{red:"#E31B23",deepRed:"#B5121B"},services:[
  {id:"haircuts",name:"Haircuts",image:"Men's haircut(Back view).jpg",services:[
    ["Men's Haircut","UGX 10,000","Men's haircut","Men's haircut(Back view).jpg"],["Women's Haircut","UGX 15,000","Women's haircut","Natural Hair styling.jpg"],["Kids Haircut","UGX 5,000","Kids haircut","kids Haircut.jpg"]]},
  {id:"nails",name:"Pedicure & Manicure",image:"Prdicure.jpg",services:[
    ["Normal","UGX 5,000","Normal manicure or pedicure","Nail painting.jpg"],["Foot Scrub","UGX 15,000 / 25,000","Foot scrub","Prdicure.jpg"],["Gel Colors Only","UGX 20,000","Gel colors only","Nail painting.jpg"],["Gel Builder","UGX 35,000","Gel builder","manicure.jpg"],["Artificial Nails + Gel Builder + Gel","UGX 70,000","Artificial nails with gel builder and gel","manicure.jpg"],["Artificial Nails + Normal Color","UGX 25,000","Artificial nails with normal color","Nail painting.jpg"]]},
  {id:"styling",name:"Hair Treatments & Styling",image:"Blow dry and styling.jpg",services:[
    ["Wash & Blow Dry","UGX 10,000","Wash and blow dry","Blow dry and styling.jpg"],["Hair Ironing","UGX 25,000","Hair ironing","Hair straightening.jpg"],["Unplaiting","UGX 10,000","Unplaiting","Braids.jpg"],["Natural Leave-in Treatments","UGX 30,000 / 25,000","Natural leave-in treatments","Natural Hair styling.jpg"],["Other Leave-in Treatments","UGX 20,000","Other leave-in treatments","Hair wash.jpg"],["Hair Steaming Treatments","UGX 30,000","Hair steaming treatments","Hair wash.jpg"]]},
  {id:"braids",name:"Braids & Plaiting",image:"Braids.jpg",services:[
    ["Cornrows Plaiting","UGX 20,000","Cornrows plaiting","Conrows.jpg"],["Cornrows with Braids","UGX 30,000","Cornrows with braids","Braids.jpg"],["Natural Hair Styling","UGX 20,000","Natural hair styling","Natural Hair styling.jpg"],["Kids Plaiting","UGX 80,000","Kids plaiting","kids Plaiting.jpg"],["Pencil Plaiting","UGX 60,000","Pencil plaiting","pencil plaiting.jpg"],["Box Braids","UGX 80,000","Box braids","Braids.jpg"],["Knotless Braids","UGX 110,000","Knotless braids","knoteless braiding.jpg"],["Passion Twists","UGX 150,000","Passion twists","Braids.jpg"],["Weave Plaiting","UGX 100,000","Weave plaiting","Weave plaiting.jpg"],["Wig Installation","UGX 50,000","Wig installation","Blow dry and styling.jpg"],["Dreadlocks Styling","UGX 50,000","Dreadlocks styling","Dreadlocks.jpg"],["Hair Coloring","UGX 40,000","Hair coloring","Hair coloring.jpg"],["Hair Retouching","Price varies","Hair retouching",""]]}
],gallery:[
  ["Salon Interior 2.jpg","Beauty Secret Salon","Our Salon"],["Men's haircut(Back view).jpg","Men's Haircut","Haircuts"],["kids Haircut.jpg","Kids Haircut","Haircuts"],["Hair tinting-Dyeing.jpg","Hair Coloring","Hair colouring"],["Conrows.jpg","Cornrows","Braids & plaiting"],["knoteless braiding.jpg","Knotless Braids","Braids & plaiting"],["Natural Hair styling.jpg","Natural Hair Styling","Hair styling"],["Blow dry and styling.jpg","Wash & Blow Dry","Treatments & styling"],["Hair wash.jpg","Hair Steaming Treatments","Treatments & styling"],["Salon Interior 4.jpg","Beauty Secret Salon","Our Salon"],["pencil plaiting.jpg","Pencil Plaiting","Braids & plaiting"],["Weave plaiting.jpg","Weave Plaiting","Braids & plaiting"],["Prdicure.jpg","Pedicure","Nails"],["manicure.jpg","Manicure","Nails"]]};
const imagePath=name=>"assets/Images/"+name;
const safe=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const whatsappMessage=service=>service[0]==="Hair Retouching"?"Hello Beauty Secret Salon, I would like to enquire about Hair Retouching. Please let me know the price and available time slots.":"Hello Beauty Secret Salon, I would like to enquire about "+service[0]+" ("+service[1]+"). Please let me know the available time slots.";
const whatsappUrl=service=>siteData.business.whatsappConfirmed?"https://wa.me/"+siteData.business.whatsappNumber+"?text="+encodeURIComponent(whatsappMessage(service)):"#contact";
const tabs=document.querySelector("#service-tabs"),catalogue=document.querySelector("#service-catalogue"),gallery=document.querySelector("#gallery-grid");
const bookingDialog=document.querySelector("#booking-dialog"),bookingForm=document.querySelector("#booking-form"),bookingName=document.querySelector("#booking-name"),bookingPhone=document.querySelector("#booking-phone"),bookingService=document.querySelector("#booking-service"),bookingNote=document.querySelector("#booking-note"),bookingPrice=document.querySelector("#booking-price"),bookingError=document.querySelector(".booking-error");
const allServices=siteData.services.flatMap(category=>category.services);
let activeService="haircuts",bookingPreviousFocus=null;
function serviceByName(name){return allServices.find(service=>service[0]===name)}
function bookingDisplayPrice(service){return service?service[1]==="Price varies"?"Price after consultation":service[1]:""}
function updateBookingPrice(){const service=serviceByName(bookingService.value);bookingPrice.textContent=bookingDisplayPrice(service)}
function populateBookingServices(){bookingService.innerHTML='<option value="">Select a service</option>'+allServices.map(service=>'<option value="'+safe(service[0])+'">'+safe(service[0])+' — '+safe(service[1])+'</option>').join("")}
function openBooking(serviceName=""){bookingPreviousFocus=document.activeElement;bookingForm.reset();bookingError.textContent="";bookingName.removeAttribute("aria-invalid");bookingPhone.removeAttribute("aria-invalid");bookingService.removeAttribute("aria-invalid");populateBookingServices();bookingService.value=serviceByName(serviceName)?serviceName:"";updateBookingPrice();bookingDialog.showModal();bookingDialog.querySelector(".booking-close").focus()}
function closeBooking(){bookingDialog.close()}
function bookingWhatsAppMessage(name,phone,service,note){const price=service[1],nl=String.fromCharCode(10);let message="Hello Beauty Secret Salon,"+nl+nl+"My name is "+name+"."+nl+nl;message+=price==="Price varies"?"I would like to enquire about Hair Retouching."+nl+nl:"I would like to book:"+nl+service[0]+" — "+price+nl+nl;message+="My phone number is "+phone+"."+nl+nl;if(note)message+="Note:"+nl+note+nl+nl;message+=price==="Price varies"?"Please let me know the price and available appointment times.":"Please let me know the available appointment times.";return message}
document.querySelectorAll("[data-booking-open]").forEach(button=>button.addEventListener("click",()=>openBooking()));
catalogue.addEventListener("click",event=>{const button=event.target.closest("[data-book-service]");if(button)openBooking(button.dataset.bookService)});
bookingService.addEventListener("change",updateBookingPrice);
bookingDialog.querySelector(".booking-close").addEventListener("click",closeBooking);
bookingDialog.addEventListener("close",()=>{bookingForm.reset();bookingPrice.textContent="";bookingError.textContent="";bookingPreviousFocus?.focus()});
bookingDialog.addEventListener("click",event=>{if(event.target===bookingDialog)closeBooking()});
bookingForm.addEventListener("submit",event=>{event.preventDefault();bookingError.textContent="";[bookingName,bookingPhone,bookingService].forEach(field=>field.removeAttribute("aria-invalid"));const name=bookingName.value.trim(),phone=bookingPhone.value.trim(),service=serviceByName(bookingService.value),note=bookingNote.value.trim();if(!name||name.length<2){bookingError.textContent="Please enter your name.";bookingName.setAttribute("aria-invalid","true");bookingName.focus();return}if(!phone||phone.replace(/[^0-9+]/g,"").length<7){bookingError.textContent="Please enter a valid phone number.";bookingPhone.setAttribute("aria-invalid","true");bookingPhone.focus();return}if(!service){bookingError.textContent="Please select a service.";bookingService.setAttribute("aria-invalid","true");bookingService.focus();return}window.location.href="https://wa.me/"+siteData.business.whatsappNumber+"?text="+encodeURIComponent(bookingWhatsAppMessage(name,phone,service,note))});

function renderTabs(){tabs.innerHTML=siteData.services.map((category,index)=>`<button type="button" role="tab" aria-selected="${category.id===activeService}" aria-controls="service-${category.id}" data-service-tab="${category.id}">${category.name}<span aria-hidden="true">↘</span></button>`).join("");tabs.querySelectorAll("[data-service-tab]").forEach(button=>button.addEventListener("click",()=>{activeService=button.dataset.serviceTab;setActiveService(activeService);document.getElementById("service-"+activeService).scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})}))}
function renderServices(){renderTabs();catalogue.innerHTML=siteData.services.map(category=>`<section class="service-category reveal visible" id="service-${category.id}" aria-labelledby="heading-${category.id}"><figure class="service-photo"><img src="${imagePath(category.image)}" alt="${safe(category.name)} at Beauty Secret Salon" loading="lazy"></figure><div class="service-list"><h3 id="heading-${category.id}">${category.name}</h3><p>Professional ${category.name.toLowerCase()} with clear pricing and direct salon enquiries.</p>${category.services.map(service=>`<article class="service-row"><div><h4>${safe(service[0])}</h4></div><div class="service-price"><strong>${safe(service[1])}</strong><button type="button" class="service-enquire" data-book-service="${safe(service[0])}">Enquire <span aria-hidden="true">↗</span></button></div></article>`).join("")}</div></section>`).join("")}
function setActiveService(id){activeService=id;tabs.querySelectorAll("[data-service-tab]").forEach(button=>{const selected=button.dataset.serviceTab===id;button.setAttribute("aria-selected",String(selected));if(selected)button.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"nearest",inline:"center"})})}
function observeServiceSections(){if(!("IntersectionObserver" in window))return;const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActiveService(visible.target.id.replace("service-",""))},{rootMargin:"-18% 0px -58% 0px",threshold:[0,.2,.5,.8]});document.querySelectorAll(".service-category").forEach(section=>observer.observe(section))}
function renderGallery(){gallery.innerHTML=siteData.gallery.map((item,index)=>`<button class="gallery-item reveal" type="button" data-gallery-index="${index}" aria-label="View ${safe(item[1])}"><span><img src="${imagePath(item[0])}" alt="${safe(item[1])} at Beauty Secret Salon" loading="lazy"><i aria-hidden="true">↗</i></span><b>${safe(item[1])}</b><small>${safe(item[2])}</small></button>`).join("");gallery.querySelectorAll("[data-gallery-index]").forEach(button=>button.addEventListener("click",()=>openGallery(+button.dataset.galleryIndex)))}
const lightbox=document.querySelector("#lightbox");let galleryIndex=0,previousFocus=null;function openGallery(index){galleryIndex=(index+siteData.gallery.length)%siteData.gallery.length;const item=siteData.gallery[galleryIndex];lightbox.querySelector("img").src=imagePath(item[0]);lightbox.querySelector("img").alt=item[1];lightbox.querySelector("figcaption").textContent=`${item[1]} / ${item[2]} — ${galleryIndex+1} of ${siteData.gallery.length}`;previousFocus=document.activeElement;if(!lightbox.open)lightbox.showModal()}
lightbox.querySelector(".lightbox-close").onclick=()=>lightbox.close();lightbox.querySelector(".lightbox-prev").onclick=()=>openGallery(galleryIndex-1);lightbox.querySelector(".lightbox-next").onclick=()=>openGallery(galleryIndex+1);lightbox.addEventListener("close",()=>previousFocus?.focus());lightbox.addEventListener("click",event=>{if(event.target===lightbox)lightbox.close()});lightbox.addEventListener("keydown",event=>{if(event.key==="ArrowLeft")openGallery(galleryIndex-1);if(event.key==="ArrowRight")openGallery(galleryIndex+1)});
const header=document.querySelector(".site-header"),menu=document.querySelector(".menu-toggle");
let menuScrollPosition=0;
function setMenuOpen(open){if(open){menuScrollPosition=window.scrollY;document.body.classList.add("menu-open");}else{if(document.body.classList.contains("menu-open")){document.body.classList.remove("menu-open");window.scrollTo(0,menuScrollPosition);}}header.classList.toggle("menu-open",open);menu.setAttribute("aria-expanded",String(open));menu.querySelector("span").textContent=open?"Close":"Menu";menu.querySelector("i").textContent=open?"×":"＋";}
menu.addEventListener("click",()=>setMenuOpen(!header.classList.contains("menu-open")));
document.querySelectorAll("#site-nav a").forEach(link=>link.addEventListener("click",event=>{event.preventDefault();const target=document.querySelector(link.getAttribute("href"));setMenuOpen(false);if(!target)return;const top=target.id==="home"?0:Math.max(0,target.getBoundingClientRect().top+window.scrollY-header.offsetHeight-16);window.scrollTo({top,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});}));
function initRevealObserver(){if("IntersectionObserver" in window){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");revealObserver.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(node=>revealObserver.observe(node))}else document.querySelectorAll(".reveal").forEach(node=>node.classList.add("visible"))}
document.querySelector("#year").textContent=new Date().getFullYear();renderServices();renderGallery();observeServiceSections();initRevealObserver();
