const siteData={business:{name:"Beauty Secret Salon",location:"Kisaasi–Kyanja Road, Kampala, Uganda",primaryPhone:"0754 852 452",secondaryPhone:"0784 852 452",whatsapp:"256754852452"},brand:{red:"#E31B23",deepRed:"#B5121B"},services:[
  {id:"haircuts",name:"Haircuts",image:"Men's haircut(Back view).jpg",services:[
    ["Men's Haircut","UGX 10,000","Men's haircut","Men's haircut(Back view).jpg"],["Women's Haircut","UGX 15,000","Women's haircut","Natural Hair styling.jpg"],["Kids Haircut","UGX 5,000","Kids haircut","kids Haircut.jpg"]]},
  {id:"nails",name:"Pedicure & Manicure",image:"Prdicure.jpg",services:[
    ["Normal","UGX 5,000","Normal manicure or pedicure","Nail painting.jpg"],["Foot Scrub","UGX 15,000 / 25,000","Foot scrub","Prdicure.jpg"],["Gel Colors Only","UGX 20,000","Gel colors only","Nail painting.jpg"],["Gel Builder","UGX 35,000","Gel builder","manicure.jpg"],["Artificial Nails + Gel Builder + Gel","UGX 70,000","Artificial nails with gel builder and gel","manicure.jpg"],["Artificial Nails + Normal Color","UGX 25,000","Artificial nails with normal color","Nail painting.jpg"]]},
  {id:"styling",name:"Hair Treatments & Styling",image:"Blow dry and styling.jpg",services:[
    ["Wash & Blow Dry","UGX 10,000","Wash and blow dry","Blow dry and styling.jpg"],["Hair Ironing","UGX 25,000","Hair ironing","Hair straightening.jpg"],["Unplaiting","UGX 10,000","Unplaiting","Braids.jpg"],["Natural Leave-in Treatments","UGX 30,000 / 25,000","Natural leave-in treatments","Natural Hair styling.jpg"],["Other Leave-in Treatments","UGX 20,000","Other leave-in treatments","Hair wash.jpg"],["Hair Steaming Treatments","UGX 30,000","Hair steaming treatments","Facial treatment.jpg"]]},
  {id:"braids",name:"Braids & Plaiting",image:"Braids.jpg",services:[
    ["Cornrows Plaiting","UGX 20,000","Cornrows plaiting","Conrows.jpg"],["Cornrows with Braids","UGX 30,000","Cornrows with braids","Braids.jpg"],["Natural Hair Styling","UGX 20,000","Natural hair styling","Natural Hair styling.jpg"],["Kids Plaiting","UGX 80,000","Kids plaiting","kids Plaiting.jpg"],["Pencil Plaiting","UGX 60,000","Pencil plaiting","pencil plaiting.jpg"],["Box Braids","UGX 80,000","Box braids","Braids.jpg"],["Knotless Braids","UGX 110,000","Knotless braids","knoteless braiding.jpg"],["Passion Twists","UGX 150,000","Passion twists","Braids.jpg"],["Weave Plaiting","UGX 100,000","Weave plaiting","Weave plaiting.jpg"],["Wig Installation","UGX 50,000","Wig installation","Hair styling.jpg"],["Dreadlocks Styling","UGX 50,000","Dreadlocks styling","Dreadlocks.jpg"],["Hair Coloring","UGX 40,000","Hair coloring","Hair coloring.jpg"],["Hair Retouching","Price varies","Hair retouching","Hair tinting-Dyeing.jpg"]]}
],gallery:[
  ["Salon Interior 3.jpg","The salon","Our space"],["Braids.jpg","The art of the braid","Braids & plaiting"],["Nail painting.jpg","Perfectly polished","Nails"],["Salon Interior 4.jpg","A welcoming moment","Our space"],["Natural Hair styling.jpg","Made for you","Hair styling"],["Men's haircut(Back view).jpg","A fresh perspective","Haircuts"]]};
const imagePath=name=>`assets/Images/${name}`;
const safe=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const whatsappMessage=service=>service==="Hair Retouching"?`Hello Beauty Secret Salon, I would like to enquire about Hair Retouching. Please let me know the price and available time slots.`:`Hello Beauty Secret Salon, I would like to enquire about ${service[0]} (${service[1]}). Please let me know the available time slots.`;
const whatsappUrl=service=>`https://wa.me/${siteData.business.whatsapp}?text=${encodeURIComponent(whatsappMessage(service))}`;
const tabs=document.querySelector("#service-tabs"),catalogue=document.querySelector("#service-catalogue"),gallery=document.querySelector("#gallery-grid");let activeService="haircuts";
function renderTabs(){tabs.innerHTML=siteData.services.map((category,index)=>`<button type="button" role="tab" aria-selected="${category.id===activeService}" aria-controls="service-${category.id}" data-service-tab="${category.id}">${category.name}<span aria-hidden="true">↘</span></button>`).join("");tabs.querySelectorAll("[data-service-tab]").forEach(button=>button.addEventListener("click",()=>{activeService=button.dataset.serviceTab;renderServices();document.querySelector(`#service-${activeService}`).scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})}))}
function renderServices(){renderTabs();catalogue.innerHTML=siteData.services.filter(category=>category.id===activeService).map(category=>`<section class="service-category reveal visible" id="service-${category.id}" aria-labelledby="heading-${category.id}"><figure class="service-photo"><img src="${imagePath(category.image)}" alt="${safe(category.name)} at Beauty Secret Salon" loading="lazy"><figcaption>${category.name.toUpperCase()}</figcaption></figure><div class="service-list"><h3 id="heading-${category.id}">${category.name}</h3><p>Professional ${category.name.toLowerCase()} with clear pricing and direct salon enquiries.</p>${category.services.map(service=>`<article class="service-row"><div><h4>${safe(service[0])}</h4><small>${safe(service[2])}</small></div><div class="service-price"><strong>${safe(service[1])}</strong><a href="${whatsappUrl(service)}" target="_blank" rel="noopener" class="service-enquire">Enquire <span aria-hidden="true">↗</span></a></div></article>`).join("")}</div></section>`).join("")}
function renderGallery(){gallery.innerHTML=siteData.gallery.map((item,index)=>`<button class="gallery-item reveal" type="button" data-gallery-index="${index}" aria-label="View ${safe(item[1])}"><span><img src="${imagePath(item[0])}" alt="${safe(item[1])} at Beauty Secret Salon" loading="lazy"><i aria-hidden="true">↗</i></span><b>${safe(item[1])}</b><small>${safe(item[2])}</small></button>`).join("");gallery.querySelectorAll("[data-gallery-index]").forEach(button=>button.addEventListener("click",()=>openGallery(+button.dataset.galleryIndex)))}
const lightbox=document.querySelector("#lightbox");let galleryIndex=0,previousFocus=null;function openGallery(index){galleryIndex=(index+siteData.gallery.length)%siteData.gallery.length;const item=siteData.gallery[galleryIndex];lightbox.querySelector("img").src=imagePath(item[0]);lightbox.querySelector("img").alt=item[1];lightbox.querySelector("figcaption").textContent=`${item[1]} / ${item[2]} — ${galleryIndex+1} of ${siteData.gallery.length}`;previousFocus=document.activeElement;if(!lightbox.open)lightbox.showModal()}
lightbox.querySelector(".lightbox-close").onclick=()=>lightbox.close();lightbox.querySelector(".lightbox-prev").onclick=()=>openGallery(galleryIndex-1);lightbox.querySelector(".lightbox-next").onclick=()=>openGallery(galleryIndex+1);lightbox.addEventListener("close",()=>previousFocus?.focus());lightbox.addEventListener("click",event=>{if(event.target===lightbox)lightbox.close()});lightbox.addEventListener("keydown",event=>{if(event.key==="ArrowLeft")openGallery(galleryIndex-1);if(event.key==="ArrowRight")openGallery(galleryIndex+1)});
const header=document.querySelector(".site-header"),menu=document.querySelector(".menu-toggle");menu.addEventListener("click",()=>{const open=header.classList.toggle("menu-open");menu.setAttribute("aria-expanded",String(open));menu.querySelector("span").textContent=open?"Close":"Menu";menu.querySelector("i").textContent=open?"×":"＋"});document.querySelectorAll("#site-nav a").forEach(link=>link.addEventListener("click",()=>{header.classList.remove("menu-open");menu.setAttribute("aria-expanded","false");menu.querySelector("span").textContent="Menu";menu.querySelector("i").textContent="＋"}));
if("IntersectionObserver" in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(node=>observer.observe(node))}else document.querySelectorAll(".reveal").forEach(node=>node.classList.add("visible"));
document.querySelector("#year").textContent=new Date().getFullYear();renderServices();renderGallery();
